import {createActions} from 'redux-actions';
import {
    SET_CHECKLIST,
    SET_CHECKLIST_SUCCESS,
    SET_CHECKLIST_FAIL,
    SET_TANK_CHECKING_RECORD,
    SET_TANK_CHECKING_RECORD_SUCCESS,
    SET_TANK_CHECKING_RECORD_FAIL,
    TAKCR,
    VALVE_FLANGE_RECORD,
    VAPORIZER_CHKREC,
    VAPO_CHK_RECORD,
    VAPORIZERCR,
    // ERTSR,
    ETHSYSRECORD,
    // FIREFGHRECORD,
    // FFRECORD,
    FREFGTREC,
    MTHCHK,
    MTHCHK_SUCCESS,
    MTHCHK_FAIL,
    GET_MTNDATE,
    MTNDATE,
    MTDATE,
    MTDATE_SUCCESS,
    MTDATE_FAIL,
    GETALLCHILD,
    GETALLCHILD_SUCCESS,
    GETALLCHILD_FAIL
} from '../types';

export const {
    setChecklist,
    setChecklistSuccess,
    setChecklistFail,
    // tankCheckingRecord,
    // tankCheckingRecordSuccess,
    // tankCheckingRecordFail,
    takcr,
    valveFlangeRecord,
    // vaporizerChkRecord,
    vapoChkRecord,
    // vaporizerCR
    // earthsysrec,
    ethsysrecord,
    // firefgtrec,
    // ffrecord,
    frefgtrec,
    mthchk,
    mthchkSuccess,
    mthchkFail,
    getmtndate,
    mtndate,
    mtdate,
    mtdateSuccess,
    mtdateFail,
    getallchild,
    getallchildSuccess,
    getallchildFail,
} = createActions({
    [SET_CHECKLIST]: (checklist) => ({checklist}),
    [SET_CHECKLIST_SUCCESS]: (respond) => ({respond}),
    [SET_CHECKLIST_FAIL]: (error) => ({error}),
    // [SET_TANK_CHECKING_RECORD]: () => ({}),
    // [SET_TANK_CHECKING_RECORD_SUCCESS]: (checkingRecord) => ({ checkingRecord }),
    // [SET_TANK_CHECKING_RECORD_FAIL]: (error_TankCheckingRecord = '') => ({
    //     error_TankCheckingRecord
    // }),
    [TAKCR]: (checkingRecord) => ({ checkingRecord }),
    [VALVE_FLANGE_RECORD]: (valveFlangeRecord) => ({ valveFlangeRecord }),
    // [VAPORIZER_CHKREC]: (vaporizerRecord) => ({ vaporizerRecord }),
    [VAPO_CHK_RECORD]: (vaporizerRecord) => ({ vaporizerRecord }),
    // [VAPORIZERCR]: (vaporizerRecord) => ({ vaporizerRecord }),
    // [ERTSR]: (earthSysRecord) => ({ earthSysRecord }),
    [ETHSYSRECORD]: (earthSysRecord) => ({ earthSysRecord }),
    // [FIREFGHRECORD]: (firefgtRecord) => ({ firefgtRecord }),    
    // [FFRECORD]: (firefgtRecord) => ({ firefgtRecord }),
    [FREFGTREC]: (firefgtRecord) => ({ firefgtRecord }),
    [MTHCHK]: (mthChecklist) => ({mthChecklist}),
    [MTHCHK_SUCCESS]: (respond) => ({respond}),
    [MTHCHK_FAIL]: (error) => ({error}),
    [GET_MTNDATE]: () => ({}),
    [MTNDATE]: () => ({}),
    [MTDATE]: (payload) => (payload),
    [MTDATE_SUCCESS]: (mtnDate) => ({mtnDate}),
    [MTDATE_FAIL]: (error) => ({error}),    
    [GETALLCHILD]: (isChildOf) => ({isChildOf}),
    [GETALLCHILD_SUCCESS]: (listChildCompany) => ({listChildCompany}),
    [GETALLCHILD_FAIL]: (error) => ({error}),
});

