platform :ios, '9.0'

target '4TeGas' do
   # Pods for 4TeGas
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # third party
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'
  pod 'RNImgToBase64', :path => '../node_modules/react-native-image-base64/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"



  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-camera-roll/camera-roll'

end
# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == "yoga"
#       target.remove_from_project
#     end

#     if target.name == "React"
#       target.remove_from_project
#     end
#   end
# end

target '4TeGas-tvOS' do
  # Pods for RnDiffApp-tvOS
  target '4TeGas-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
