import { constant } from "lodash";
import { exp } from "react-native-reanimated";

export const LOG_OUT = "LOG_OUT";
// Auth actions
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const GET_STATISTICS = "GET_STATISTICS";
export const GET_STATISTICS_RESULT = "GET_STATISTICS_RESULT";
export const GET_STATISTICS_ERR = "GET_STATISTICS_ERR";

// Cuong them vao
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const GET_LIST_DRIVER = "GET_LIST_DRIVER";
export const GET_LIST_DRIVER_SUCCESS = "GET_LIST_DRIVER_SUCCESS";
export const GET_LIST_DRIVER_FAIL = "GET_LIST_DRIVER_FAIL";
export const GET_SIGNATURE = "GET_SIGNATURE";
export const GET_SIGNATURE_SUCCESS = "GET_SIGNATURE_SUCCESS";
export const GET_SIGNATURE_FAIL = "GET_SIGNATURE_FAIL";
export const RETURN_GAS = "RETURN_GAS";
export const RETURN_GAS_SUCCESS = "RETURN_GAS_SUCCESS";
export const RETURN_GAS_FAIL = "RETURN_GAS_FAIL";
export const SET_CHECKLIST = "SET_CHECKLIST";
export const SET_CHECKLIST_SUCCESS = "SET_CHECKLIST_SUCCESS";
export const SET_CHECKLIST_FAIL = "SET_CHECKLIST_FAIL";
export const SET_TANK_CHECKING_RECORD = "SET_TANK_CHECKING_RECORD";
export const SET_TANK_CHECKING_RECORD_SUCCESS =
  "SET_TANK_CHECKING_RECORD_SUCCESS";
export const SET_TANK_CHECKING_RECORD_FAIL = "SET_TANK_CHECKING_RECORD_FAIL";
export const SET_LIST_ORDER = "SET_LIST_ORDER";
export const GET_LIST_STORE_RESULT = "GET_LIST_STORE_RESULT";
export const GET_LIST_STORE_ERR = "GET_LIST_STORE_ERR";
export const SET_NEW_ORDER = "SET_NEW_ORDER";
export const SET_NEW_ORDER_SUCCESS = "SET_NEW_ORDER_SUCCESS";
export const GET_LIST_STORE_CODE = "GET_LIST_STORE_CODE";
export const GET_LIST_STORE_CODE_RESULT = "GET_LIST_STORE_CODE_RESULT";
export const TAKCR = "TAKCR";
export const VALVE_FLANGE_RECORD = "VALVE_FLANGE_RECORD";
export const VAPORIZER_CHKREC = "VAPORIZER_CHKREC";
export const VAPO_CHK_RECORD = "VAPO_CHK_RECORD";
export const VAPORIZERCR = "VAPORIZERCR";
export const ERTSR = "ERTSR";
export const ETHSYSRECORD = "ETHSYSRECORD";
export const FIREFGHRECORD = "FIREFGHRECORD";
export const FFRECORD = "FFRECORD";
export const FREFGTREC = "FREFGTREC";
export const MTHCHK = "MTHCHK";
export const MTHCHK_SUCCESS = "MTHCHK_SUCCESS";
export const MTHCHK_FAIL = "MTHCHK_FAIL";
export const GET_MTNDATE = "GET_MTNDATE";
export const MTNDATE = "MTNDATE";
export const MTDATE = "MTDATE";
export const MTDATE_SUCCESS = "MTDATE_SUCCESS";
export const MTDATE_FAIL = "MTDATE_FAIL";
export const GETALLCHILD = "GETALLCHILD";
export const GETALLCHILD_SUCCESS = "GETALLCHILD_SUCCESS";
export const GETALLCHILD_FAIL = "GETALLCHILD_FAIL";
export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const GET_ORDER = "GET_ORDER";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAIL = "UPDATE_ORDER_STATUS_FAIL";
export const GET_ORDER_FACTORY = "GET_ORDER_FACTORY";
export const GET_ORDER_FACTORY_SUCCESS = "GET_ORDER_FACTORY_SUCCESS";
export const GET_ORDER_FACTORY_FAIL = "GET_ORDER_FACTORY_FAIL";
export const GET_LST_CYLINDER = "GET_LST_CYLINDER";
export const GET_LST_CYLINDER_SUCCESS = "GET_LST_CYLINDER_SUCCESS";
export const GET_LST_CYLINDER_FAIL = "GET_LST_CYLINDER_FAIL";
export const GET_LIST_BY_CUSTOMER_TYPE = "GET_LIST_BY_CUSTOMER_TYPE";
export const GET_LIST_BY_CUSTOMER_TYPE_SUCCESS =
  "GET_LIST_BY_CUSTOMER_TYPE_SUCCESS";
export const GET_LIST_BY_CUSTOMER_TYPE_FAIL = "GET_LIST_BY_CUSTOMER_TYPE_FAIL";
export const GET_LIST_BRANCH = "GET_LIST_BRANCH";
export const GET_LIST_BRANCH_SUCCESS = "GET_LIST_BRANCH_SUCCESS";
export const GET_LIST_BRANCH_FAIL = "GET_LIST_BRANCH_FAIL";
export const GET_LIST_TRUCK = "GET_LIST_TRUCK";
export const GET_LIST_TRUCK_SUCCESS = "GET_LIST_TRUCK_SUCCESS";
export const GET_LIST_TRUCK_FAIL = "GET_LIST_TRUCK_FAIL";
export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAIL = "GET_USER_INFO_FAIL";
export const GET_LIST_CUSTOMER_TYPE = "GET_LIST_CUSTOMER_TYPE";
export const GET_LIST_CUSTOMER_TYPE_SUCCESS = "GET_LIST_CUSTOMER_TYPE_SUCCESS";
export const GET_LIST_CUSTOMER_TYPE_FAIL = "GET_LIST_CUSTOMER_TYPE_FAIL";

//Phat test
export const GET_LST_WEIGHT = "GET_LST_WEIGHT";
export const GET_LST_WEIGHT_SUCCESS = "GET_LST_WEIGHT_SUCCESS";
export const GET_LST_WEIGHT_FAIL = "GET_LST_WEIGHT_FAIL";

//userTypes
export const TONG_CONG_TY = "Tong_cong_ty";
export const TRAM = "Tram";
export const KHACH_HANG = "Khach_hang";
// userRoles
export const DELIVER = "Deliver";
export const TRUCK = "Truck";
export const SALESMANAGER = "Truong_phongKD";
export const TNL = "To_nhan_lenh";
export const DDTM = "phongKD";
export const KT = "Ke_toan";
export const KTVB = "Ke_toan_vo_binh";
export const KT_TRAM = "Ke_toan_tram";
export const PGD = "Pho_giam_docKD";
export const DDT = "Dieu_do_tram";
export const TRUONG_TRAM = "Truong_tram";
export const GIAM_DOC = "Giam_doc";
export const INSPECTOR = "Inspector";
export const OWNER = "Owner";

// Cyclinder actions

export const FETCH_CYLINDER = "FETCH_CYLINDER";
export const FETCH_CYLINDER_SUCCESS = "FETCH_CYLINDER_SUCCESS";
export const FETCH_CYLINDER_FAIL = "FETCH_CYLINDER_FAIL";

export const REPORT_CYCLINDER = "REPORT_CYCLINDER";
export const REPORT_CYCLINDER_SUCCESS = "REPORT_CYCLINDER_SUCCESS";
export const REPORT_CYCLINDER_FAIL = "REPORT_CYCLINDER_FAIL";

export const CHANGE_CYCLINDER_ACTION = "CHANGE_CYCLINDER_ACTION";
export const ADD_CYLINDER = "ADD_CYLINDER";
export const DELETE_CYLINDERS = "DELETE_CYLINDERS";
// export const TURN_BACK_CYCLINDER = 'TURN_BACK_CYCLINDER';

export const UPDATE_CYLINDERS = "UPDATE_CYLINDERS";
export const UPDATE_CYLINDERS_SUCCESS = "UPDATE_CYLINDERS_SUCCESS";
export const UPDATE_CYLINDERS_FAIL = "UPDATE_CYLINDERS_FAIL";

export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const EXPORT_PLACE = "EXPORT_PLACE";
export const EXPORT_PLACE_SUCCESS = "EXPORT_PLACE_SUCCESS";
export const EXPORT_PLACE_FAIL = "EXPORT_PLACE_FAIL";

export const TYPE_FOR_PARTNER = "TYPE_FOR_PARTNER";
//report
export const REPORT = "REPORT";
export const REPORT_SUCCESS = "REPORT_SUCCESS";
export const REPORT_FAIL = "REPORT_FAIL";
export const REPORT_CHART = "REPORT_CHART";
export const REPORT_CHART_SUCCESS = "REPORT_CHART_SUCCESS";
export const REPORT_CHART_FAIL = "REPORT_CHART_FAIL";
//Fetch user typeForPartner
export const FETCH_USERS_TYPE_FOR_PARTNER = "FETCH_USERS_TYPE_FOR_PARTNER";
export const IN_REPAIR = "IN_REPAIR";
export const STATION = "Station";
export const FACTORY = "Factory";
export const GENERAL = "General";
export const AGENCY = "Agency";
export const GOVERNMENT = "Government";
export const SUPER_ADMIN = "SuperAdmin";
export const EXPORT_PARTNER = "EXPORT_PARTNER";
export const BUY = "BUY";
export const RENT = "RENT";
export const TO_FIX = "TO_FIX";
export const FIXER = "Fixer";
export const RETURN_CYLINDER = "RETURN_CYLINDER";
export const IMPORT = "IMPORT";
export const EXPORT = "EXPORT";
export const EXPORT_PARENT_CHILD = "EXPORT_PARENT_CHILD";
export const TURN_BACK = "TURN_BACK";
export const DAILY_REPORT = "dailyReport";

export const DAILY_REPORTNEW = "statisticManager";
export const DAILY_REPORTNEW_VER2 = "statisticManagerVer2";
export const DAILY_REPORTNEW_VER3 = "statisticManagerVer3";
export const VEHICLE_INVENTORY_STATISTICS = "StatisticManagerWarehouse";
export const WAREHOUSE_MANAGER = "warehouseAccount";
export const CHOOSE_SCAN = "ChooseScan";

export const IN_CUSTOMER = "IN_CUSTOMER";
export const IN_FACTORY = "IN_FACTORY";
export const DELIVERING = "DELIVERING";
export const TURN_BACK_MARKET = "TURN_BACK_MARKET";
export const TURN_BACK_SALE_FROM_PARTNER = "TURN_BACK_SALE_FROM_PARTNER";
export const TURN_BACK_RENT_FROM_PARTNER = "TURN_BACK_RENT_FROM_PARTNER";
export const TURN_BACK_FROM_FACTORY_REPAIR = "TURN_BACK_FROM_FACTORY_REPAIR";
export const EXPORT_CYLINDER_EMPTY = "EXPORT_CYLINDER_EMPTY";
export const REPORT_CHART_BAR = "REPORT_CHART_BAR";
export const REPORT_CHART_BAR_SUCCESS = "REPORT_CHART_BAR_SUCCESS";
export const REPORT_CHART_BAR_FAIL = "REPORT_CHART_BAR_FAIL";
export const currencyFormat = (num) => {
  return num.replace(/(\d)(?=(\d{3})+(?!\d))/g, "1.");
};
//statisticsReport
export const GET_Export = "GET_Export";
export const GET_Export_SUCCESS = "GET_Export_SUCCESS";
export const GET_Export_FAIL = "GET_Export_FAIL";
export const GCIT = "GCIT";
export const GCITS = "GCITS";
export const GCITF = "GCITF";
export const GSTT = "GSTT";
export const GSTTS = "GSTTS";
export const GSTTF = "GSTTF";

//G.hoa them
export const GET_LST_WARE_HOUSES = "GET_LST_WARE_HOUSES";
export const GET_LST_WARE_HOUSES_SUCCESS = "GET_LST_WARE_HOUSES_SUCCESS";
export const GET_LST_WARE_HOUSES_FAIL = "GET_LST_WARE_HOUSES_FAIL";
export const GET_LST_REGION = "GET_LST_REGION";
export const GET_LST_REGION_SUCCESS = "GET_LST_REGION_SUCCESS";
export const GET_LST_REGION_FAIL = "GET_LST_REGION_FAIL";
export const GET_Export_CYLINDER_SUCCESS = "GET_Export_CYLINDER_SUCCESS";
export const GET_Import_CYLINDER_SUCCESS = "GET_Import_CYLINDER_SUCCESS";
export const GET_LIST_STATION = "GET_LIST_STATION";
export const GET_LIST_STATION_SUCCESS = "GET_LIST_STATION_SUCCESS";
export const GET_LIST_MANUFACTURE = "GET_LIST_MANUFACTURE";
export const GET_LIST_MANUFACTURE_RESULT = "GET_LIST_MANUFACTURE_RESULT";

export const ORDERS = "ORDERS";
export const SET_ORDER = "SET_ORDER";
export const SET_ORDER_SUCCESS = "SET_ORDER_SUCCESS";
export const SET_ORDER_FAIL = "SET_ORDER_FAIL";
export const GET_COMPLETED_ORDER_AND_CYLINDERS =
  "GET_COMPLETED_ORDER_AND_CYLINDERS";
export const GET_COMPLETED_ORDER_AND_CYLINDERS_SUCCESS =
  "GET_COMPLETED_ORDER_AND_CYLINDERS_SUCCESS";
export const GET_COMPLETED_ORDER_AND_CYLINDERS_FAIL =
  "GET_COMPLETED_ORDER_AND_CYLINDERS_FAIL";

//Hang
export const APPROVAL_ORDER = "APPROVAL_ORDER";
export const APPROVAL_ORDER_SUCCESS = "APPROVAL_ORDER_SUCCESS";
export const APPROVAL_ORDER_FAIL = "APPROVAL_ORDER_FAIL";
export const CANCEL_ORDER = "CANCEL-ORDER";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAIL = "CANCEL_ORDER_FAIL";

//linh
export const SET_ORDER_REQUEST = "SET_ORDER_REQUEST";
export const SET_ORDER_REQUEST_SUCCESS = "SET_ORDER_REQUEST_SUCCESS";
export const SET_ORDER_REQUEST_FAIL = "SET_ORDER_REQUEST_FAIL";
export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_REQUEST_SUCCESS = "GET_ORDER_REQUEST_SUCCESS";
export const GET_ORDER_REQUEST_FAIL = "GET_ORDER_REQUEST_FAIL";
//driver
export const DRIVER_TAB = "DRIVER_TAB";

export const GET_ALL_SHIPPING_ORDER_INIT = "GET_ALL_SHIPPING_ORDER_INIT";
export const GET_ALL_SHIPPING_ORDER_INIT_SUCCESS =
  "GET_ALL_SHIPPING_ORDER_INIT_SUCCESS";
export const GET_ALL_SHIPPING_ORDER_INIT_FAIL =
  "GET_ALL_SHIPPING_ORDER_INIT_FAIL";
export const GET_ALL_SHIPPING_ORDER_TANK_INIT =
  "GET_ALL_SHIPPING_ORDER_TANK_INIT";
export const GET_ALL_SHIPPING_ORDER_TANK_INIT_SUCCESS =
  "GET_ALL_SHIPPING_ORDER_TANK_INIT_SUCCESS";
export const GET_ALL_SHIPPING_ORDER_TANK_INIT_FAIL =
  "GET_ALL_SHIPPING_ORDER_TANK_INIT_FAIL";

export const GET_ALL_SHIPPING_ORDER_DETAIL_INIT =
  "GET_ALL_SHIPPING_ORDER_DETAIL_INIT";
export const GET_ALL_SHIPPING_ORDER_DETAIL_INIT_SUCCESS =
  "GET_ALL_SHIPPING_ORDER_DETAIL_INIT_SUCCESS";
export const GET_ALL_SHIPPING_ORDER_DETAIL_INIT_FAIL =
  "GET_ALL_SHIPPING_ORDER_DETAIL_INIT_FAIL";

export const GET_ALL_SHIPPING_ORDER_TANK_DETAIL_INIT =
  "GET_ALL_SHIPPING_ORDER_TANK_DETAIL_INIT";
export const GET_ALL_SHIPPING_ORDER_TANK_DETAIL_INIT_SUCCESS =
  "GET_ALL_SHIPPING_ORDER_TANK_DETAIL_INIT_SUCCESS";
export const GET_ALL_SHIPPING_ORDER_TANK_DETAIL_INIT_FAIL =
  "GET_ALL_SHIPPING_ORDER_TANK_DETAIL_INIT_FAIL";

export const GET_UPDATE_SHIPPING_ORDER_DETAIL_INIT =
  "GET_UPDATE_SHIPPING_ORDER_DETAIL_INIT";
export const GET_UPDATE_SHIPPING_ORDER_DETAIL_INIT_SUCCESS =
  "GET_UPDATE_SHIPPING_ORDER_DETAIL_INIT_SUCCESS";
export const GET_UPDATE_SHIPPING_ORDER_DETAIL_INIT_FAIL =
  "GET_UPDATE_SHIPPING_ORDER_DETAIL_INIT_FAIL";
//thay doi trang thai don hang xe bon tai xe
export const GET_UPDATE_SHIPPING_ORDER_TANK_DETAIL_INIT =
  "GET_UPDATE_SHIPPING_ORDER_TANK_DETAIL_INIT";
export const GET_UPDATE_SHIPPING_ORDER_TANK_DETAIL_INIT_SUCCESS =
  "GET_UPDATE_SHIPPING_ORDER_TANK_DETAIL_INIT_SUCCESS";
export const GET_UPDATE_SHIPPING_ORDER_TANK_DETAIL_INIT_FAIL =
  "GET_UPDATE_SHIPPING_ORDER_TANK_DETAIL_INIT_FAIL";
//tao vi tri
export const SET_CREATE_SHIPPING_ORDER_LOCATION =
  "SET_CREATE_SHIPPING_ORDER_LOCATION";
export const SET_CREATE_SHIPPING_ORDER_LOCATION_SUCCESS =
  "SET_CREATE_SHIPPING_ORDER_LOCATION_SUCCESS";
export const SET_CREATE_SHIPPING_ORDER_LOCATION_FAIL =
  "SET_CREATE_SHIPPING_ORDER_LOCATION_FAIL";

export const SET_CREATE_SHIPPING_ORDER_TANK_LOCATION =
  "SET_CREATE_SHIPPING_ORDER_TANK_LOCATION";
export const SET_CREATE_SHIPPING_ORDER_TANK_LOCATION_SUCCESS =
  "SET_CREATE_SHIPPING_ORDER_TANK_LOCATION_SUCCESS";
export const SET_CREATE_SHIPPING_ORDER_TANK_LOCATION_FAIL =
  "SET_CREATE_SHIPPING_ORDER_TANK_LOCATION_FAIL";

export const GET_CREATE_SHIPPING_ORDER_LOCATION =
  "GET_CREATE_SHIPPING_ORDER_LOCATION";
export const GET_CREATE_SHIPPING_ORDER_LOCATION_SUCCESS =
  "GET_CREATE_SHIPPING_ORDER_LOCATION_SUCCESS";
export const GET_CREATE_SHIPPING_ORDER_LOCATION_FAIL =
  "GET_CREATE_SHIPPING_ORDER_LOCATION_FAIL";

export const GET_LST_CHILDS = "GET_LST_CHILDS";
export const GET_LST_CHILDS_SUCCESS = "GET_LST_CHILDS_SUCCESS";
export const GET_LST_CHILDS_FAIL = "GET_LST_CHILDS_FAIL";

export const GET_DUPLICATE_CYLINDER = "GET_DUPLICATE_CYLINDER";
export const GET_DUPLICATE_CYLINDER_SUCCESS = "GET_DUPLICATE_CYLINDER_SUCCESS";
export const GET_DUPLICATE_CYLINDER_FAIL = "GET_DUPLICATE_CYLINDER_FAIL";

export const IMPORT_DUP_CYLINDER = "IMPORT_DUP_CYLINDER";
export const IMPORT_DUP_CYLINDER_SUCCESS = "IMPORT_DUP_CYLINDER_SUCCESS";
export const IMPORT_DUP_CYLINDER_FAIL = "IMPORT_DUP_CYLINDER_FAIL";

export const GET_ALL_ORDER_TANK_TRUCK = "GET_ORDER_TANK_TRUCK";
export const GET_ALL_ORDER_TANK_TRUCK_SUCCESS = "GET_ORDER_TANK_TRUCK_SUCCESS";
export const GET_ALL_ORDER_TANK_TRUCK_FAIL = "GET_ORDER_TANK_TRUCK_FAIL";

//Driver Bao them moi
export const TEST123 = "TEST123";
export const TYPE_REFLUX = "TYPE_REFLUX";
export const STORE_SERIAL = "STORE_SERIAL";
export const IS_CHILD_OF = "IS_CHILD_OF";

export const TYPE_DELIVERY = "TYPE_DELIVERY";
export const DELIVERY_STORE_SERIAL = "DELIVERY_STORE_SERIAL";
export const DELIVERY_DELETE_SERIAL = "DELIVERY_DELETE_SERIAL";
export const RELUX_DELETE_SERIAL = "RELUX_DELETE_SERIAL";
export const STORE_ORDER_SELECTION = "STORE_ORDER_SELECTION";
export const DRIVER_RESET_LIST_SERIAL_ORDER = "DRIVER_RESET_LIST_SERIAL_ORDER";
export const DRIVER_RESET_LIST_SERIAL_RELUX = "DRIVER_RESET_LIST_SERIAL_REFLUX";

export const CURRENT_SIGNATURE = "CURRENT_SIGNATURE";
export const DELETE_SIGNATURE = "DELETE_SIGNATURE";
export const IS_DISABLE_SIGNATURE = "IS_DISABLE_SIGNATURE";

//du them
export const LIST_ORDER = "LIST_ORDER";
export const LIST_DELIVERY_STATISTICS = "LIST_DELIVERY_STATISTICS";

//TRUCK Thuong them
export const TRUCK_TYPE_DELIVERY = "TRUCK_TYPE_DELIVERY";
export const TRUCK_DELIVERY_STORE_SERIAL = "TRUCK_DELIVERY_STORE_SERIAL";
export const TRUCK_DELIVERY_DELETE_SERIAL = "TRUCK_DELIVERY_DELETE_SERIAL";
export const TRUCK_RELUX_DELETE_SERIAL = "TRUCK_RELUX_DELETE_SERIAL";
export const TRUCK_STORE_ORDER_SELECTION = "TRUCK_STORE_ORDER_SELECTION";
export const TRUCK_RESET_LIST_SERIAL_ORDER = "TRUCK_RESET_LIST_SERIAL_ORDER";
export const TRUCK_RESET_LIST_SERIAL_RELUX = "TRUCK_RESET_LIST_SERIAL_REFLUX";
