import { createActions } from 'redux-actions';
import {
    CREATE_ORDER,
    CREATE_ORDER_SUCCESS,
    CREATE_ORDER_FAIL,
    GET_ORDER,
    GET_ORDER_SUCCESS,
    GET_ORDER_FAIL,
    GET_ORDER_HISTORY,
    GET_ORDER_HISTORY_SUCCESS,
    GET_ORDER_HISTORY_FAIL,
    UPDATE_ORDER_STATUS,
    UPDATE_ORDER_STATUS_SUCCESS,
    UPDATE_ORDER_STATUS_FAIL,
    GET_ORDER_FACTORY,
    GET_ORDER_FACTORY_SUCCESS,
    GET_ORDER_FACTORY_FAIL,
    GET_LST_WARE_HOUSES,
    GET_LST_WARE_HOUSES_SUCCESS,
    GET_LST_WARE_HOUSES_FAIL,
    SET_ORDER,
    SET_ORDER_SUCCESS,
    SET_ORDER_FAIL,
    GET_LIST_STORE,
    GET_LIST_STORE_RESULT,
    GET_LIST_STORE_ERR,
    GET_LIST_STORE_CODE,
    GET_LIST_STORE_CODE_RESULT,
    SET_NEW_ORDER,
    SET_NEW_ORDER_SUCCESS,
    SET_LIST_ORDER,
    GET_COMPLETED_ORDER_AND_CYLINDERS,
    GET_COMPLETED_ORDER_AND_CYLINDERS_SUCCESS,
    GET_COMPLETED_ORDER_AND_CYLINDERS_FAIL,
    SET_ORDER_REQUEST,
    SET_ORDER_REQUEST_SUCCESS,
    SET_ORDER_REQUEST_FAIL,
    GET_ORDER_REQUEST,
    GET_ORDER_REQUEST_SUCCESS,
    GET_ORDER_REQUEST_FAIL,
    APPROVAL_ORDER,
    APPROVAL_ORDER_SUCCESS,
    APPROVAL_ORDER_FAIL,
    CANCEL_ORDER,
    CANCEL_ORDER_SUCCESS,
    CANCEL_ORDER_FAIL,
    GET_ALL_SHIPPING_ORDER_INIT,
    GET_ALL_SHIPPING_ORDER_INIT_SUCCESS,
    GET_ALL_SHIPPING_ORDER_INIT_FAIL,
    GET_ALL_SHIPPING_ORDER_TANK_INIT,
    GET_ALL_SHIPPING_ORDER_TANK_INIT_SUCCESS,
    GET_ALL_SHIPPING_ORDER_TANK_INIT_FAIL,
    GET_ALL_SHIPPING_ORDER_DETAIL_INIT,
    GET_ALL_SHIPPING_ORDER_DETAIL_INIT_SUCCESS,
    GET_ALL_SHIPPING_ORDER_DETAIL_INIT_FAIL,
    GET_ALL_SHIPPING_ORDER_TANK_DETAIL_INIT,
    GET_ALL_SHIPPING_ORDER_TANK_DETAIL_INIT_SUCCESS,
    GET_ALL_SHIPPING_ORDER_TANK_DETAIL_INIT_FAIL,

    GET_UPDATE_SHIPPING_ORDER_DETAIL_INIT,
    GET_UPDATE_SHIPPING_ORDER_DETAIL_INIT_SUCCESS,
    GET_UPDATE_SHIPPING_ORDER_DETAIL_INIT_FAIL,

    //thay doi trang thai don hang tai xe xe bon
    GET_UPDATE_SHIPPING_ORDER_TANK_DETAIL_INIT,
    GET_UPDATE_SHIPPING_ORDER_TANK_DETAIL_INIT_SUCCESS,
    GET_UPDATE_SHIPPING_ORDER_TANK_DETAIL_INIT_FAIL,
    
    SET_CREATE_SHIPPING_ORDER_LOCATION,//tao vi tri
    SET_CREATE_SHIPPING_ORDER_LOCATION_SUCCESS,
    SET_CREATE_SHIPPING_ORDER_LOCATION_FAIL,

    SET_CREATE_SHIPPING_ORDER_TANK_LOCATION,//tao vi tri tai xe xe bon
    SET_CREATE_SHIPPING_ORDER_TANK_LOCATION_SUCCESS,
    SET_CREATE_SHIPPING_ORDER_TANK_LOCATION_FAIL,
    
    GET_CREATE_SHIPPING_ORDER_LOCATION,
    GET_CREATE_SHIPPING_ORDER_LOCATION_SUCCESS,
    GET_CREATE_SHIPPING_ORDER_LOCATION_FAIL,

    GET_LST_CHILDS,
    GET_LST_CHILDS_SUCCESS,
    GET_LST_CHILDS_FAIL,
} from '../types';

export const {
    // Cuong them vao
    setListOrder,
    setNewOrder,
    setNewOrderSuccess,
    getListStoreCodeResult,
    getListStoreCode,
    createOrder,
    createOrderSuccess,
    createOrderFail,
    getOrder,
    getListStoreResult,
    getListStoreErr,
    getOrderSuccess,
    getOrderFail,
    getOrderHistory,
    getOrderHistorySuccess,
    getOrderHistoryFail,
    updateOrderStatus,
    updateOrderStatusSuccess,
    updateOrderStatusFail,
    getOrderFactory,
    getOrderFactorySuccess,
    getOrderFactoryFail,
    getLstWareHouses,
    getLstWareHousesSuccess,
    getLstWareHousesFail,
    setOrder,
    setOrderSuccess,
    setOrderFail,
    getCompletedOrderAndCylinders,
    getCompletedOrderAndCylindersSuccess,
    getCompletedOrderAndCylindersFail,
    setOrderRequest,    //linh
    setOrderRequestSuccess,
    setOrderRequestFail,
    getOrderRequest,    //linh
    getOrderRequestSuccess,
    getOrderRequestFail,
    approvalOrder,
    approvalOrderSuccess,
    approvalOrderFail,
    cancelOrder,
    cancelOrderSuccess,
    cancelOrderFail,
    getAllShippingOrderInit,//linh driver
    getAllShippingOrderInitSuccess,
    getAllShippingOrderInitFail,
    getAllShippingOrderTankInit,//linh driver
    getAllShippingOrderTankInitSuccess,
    getAllShippingOrderTankInitFail,
    getAllShippingOrderDetailInit,//linh
    getAllShippingOrderDetailInitSuccess,
    getAllShippingOrderDetailInitFail,
    getAllShippingOrderTankDetailInit,//linh DRIVER DETAIL TANK
    getAllShippingOrderTankDetailInitSuccess,
    getAllShippingOrderTankDetailInitFail,
    getUpdateShippingOrderDetailInit,//thay doi trang thai don tai xe van chuyen
    getUpdateShippingOrderDetailInitSuccess,
    getUpdateShippingOrderDetailInitFail,
    getUpdateShippingOrderTankDetailInit,//thay doi tang thai don tai xe xe bon
    getUpdateShippingOrderTankDetailInitSuccess,
    getUpdateShippingOrderTankDetailInitFail,
    setCreateShippingOrderLocation,//tao vi tri tai xe van chuyen
    setCreateShippingOrderLocationSuccess,
    setCreateShippingOrderLocationFail,
    setCreateShippingOrderTankLocation,//tao vi tri tai xe xe bon
    setCreateShippingOrderTankLocationSuccess,
    setCreateShippingOrderTankLocationFail,
    getCreateShippingOrderLocation,
    getCreateShippingOrderLocationSuccess,
    getCreateShippingOrderLocationFail,
    getLstChilds,
    getLstChildsSuccess,
    getLstChildsFail,
} = createActions({
    // Cuong them vao
    [SET_LIST_ORDER]: (listOrder) => ({ listOrder }),
    [SET_NEW_ORDER]: (userId, createOrder) => ({ userId, createOrder }),
    [SET_NEW_ORDER_SUCCESS]: (orderSuccess) => ({ orderSuccess }),
    [GET_LIST_STORE_CODE_RESULT]: (dataCodeReult) => ({ dataCodeReult }),
    [GET_LIST_STORE_CODE]: (reqListCustomer) => ({ reqListCustomer }),
    [CREATE_ORDER]: (createOrder) => ({ createOrder }),
    [CREATE_ORDER_SUCCESS]: (resultOrder) => ({ resultOrder }),
    [CREATE_ORDER_FAIL]: (error) => ({ error }),
    [GET_LIST_STORE_RESULT]: (result) => ({ result }),
    [GET_LIST_STORE_ERR]: (err) => ({ err }),
    [GET_ORDER]: (userId) => ({ userId }),
    [GET_ORDER_SUCCESS]: (resultGetOrder) => ({ resultGetOrder }),
    [GET_ORDER_FAIL]: (error) => ({ error }),
    [GET_ORDER_HISTORY]: (orderId) => ({ orderId }),
    [GET_ORDER_HISTORY_SUCCESS]: (resultGetOrderHistory) => ({ resultGetOrderHistory }),
    [GET_ORDER_HISTORY_FAIL]: (error) => ({ error }),
    [UPDATE_ORDER_STATUS]: (updateOrderStatus) => ({ updateOrderStatus }),
    [UPDATE_ORDER_STATUS_SUCCESS]: (result_updateOrderStatus) => ({ result_updateOrderStatus }),
    [UPDATE_ORDER_STATUS_FAIL]: (error) => ({ error }),
    [GET_ORDER_FACTORY]: (userId) => ({ userId }),
    [GET_ORDER_FACTORY_SUCCESS]: (result_getOrderFactory) => ({ result_getOrderFactory }),
    [GET_ORDER_FACTORY_FAIL]: (error) => ({ error }),
    [GET_LST_WARE_HOUSES]: (isChildOf) => ({ isChildOf }),
    [GET_LST_WARE_HOUSES_SUCCESS]: (result_getWareHouse) => ({ result_getWareHouse }),
    [GET_LST_WARE_HOUSES_FAIL]: (error) => ({ error }),
    [SET_ORDER]: (createOrder, userId) => ({ createOrder, userId }),
    [SET_ORDER_SUCCESS]: (result_setOrder) => ({ result_setOrder }),
    [SET_ORDER_FAIL]: (error) => ({ error }),
    [GET_COMPLETED_ORDER_AND_CYLINDERS]: (orderId) => ({ orderId }),
    [GET_COMPLETED_ORDER_AND_CYLINDERS_SUCCESS]: (result_GetCompletedOrderAndCylinders) => ({ result_GetCompletedOrderAndCylinders }),
    [GET_COMPLETED_ORDER_AND_CYLINDERS_FAIL]: (error) => ({ error }),
    [SET_ORDER_REQUEST]: (orderShippingId, userId) => ({ orderShippingId, userId }),    //linh
    [SET_ORDER_REQUEST_SUCCESS]: (result_setOrderRequest) => ({ result_setOrderRequest }),
    [SET_ORDER_REQUEST_FAIL]: (error) => ({ error }),
    [GET_ORDER_REQUEST]: (title, data, appname, device,iddata) => ({ title, data, appname, device,iddata}),   //linh
    [GET_ORDER_REQUEST_SUCCESS]: (result_getOrderRequest) => ({ result_getOrderRequest }),
    [GET_ORDER_REQUEST_FAIL]: (error) => ({ error }),
    [APPROVAL_ORDER]: (orderShippingId, userId) => ({ orderShippingId, userId }),
    [APPROVAL_ORDER_SUCCESS]: (result_approvalOrder) => ({ result_approvalOrder }),
    [APPROVAL_ORDER_FAIL]: (error) => ({ error }),
    [CANCEL_ORDER]: (orderShippingId, userId, reasonForCancellatic) => ({ orderShippingId, userId, reasonForCancellatic }),
    [CANCEL_ORDER_SUCCESS]: (result_cancelOrder) => ({ result_cancelOrder }),
    [CANCEL_ORDER_FAIL]: (error) => ({ error }),
    [GET_ALL_SHIPPING_ORDER_INIT]: (userid) => ({ userid }),
    [GET_ALL_SHIPPING_ORDER_INIT_SUCCESS]: (result_GetAllShippingOrderInit) => ({ result_GetAllShippingOrderInit }),
    [GET_ALL_SHIPPING_ORDER_INIT_FAIL]: (error) => ({ error }),
    [GET_ALL_SHIPPING_ORDER_TANK_INIT]: (userid) => ({ userid }),
    [GET_ALL_SHIPPING_ORDER_TANK_INIT_SUCCESS]: (result_GetAllShippingOrderTankInit) => ({ result_GetAllShippingOrderTankInit }),
    [GET_ALL_SHIPPING_ORDER_TANK_INIT_FAIL]: (error) => ({ error }),
    [GET_ALL_SHIPPING_ORDER_DETAIL_INIT]: (shippingorderId) => ({ shippingorderId }),
    [GET_ALL_SHIPPING_ORDER_DETAIL_INIT_SUCCESS]: (result_GetAllShippingOrderDetailInit) => ({ result_GetAllShippingOrderDetailInit }),
    [GET_ALL_SHIPPING_ORDER_DETAIL_INIT_FAIL]: (error) => ({ error }),
    [GET_ALL_SHIPPING_ORDER_TANK_DETAIL_INIT]: (exportOrderID) => ({ exportOrderID }),//driver tank
    [GET_ALL_SHIPPING_ORDER_TANK_DETAIL_INIT_SUCCESS]: (result_GetAllShippingOrderTankDetailInit) => ({ result_GetAllShippingOrderTankDetailInit }),
    [GET_ALL_SHIPPING_ORDER_TANK_DETAIL_INIT_FAIL]: (error) => ({ error }),

    [GET_UPDATE_SHIPPING_ORDER_DETAIL_INIT]: (updateOrderStatus) => ({ updateOrderStatus}),
    [GET_UPDATE_SHIPPING_ORDER_DETAIL_INIT_SUCCESS]: (result_UpdateShippingOrderDetailInit) => ({ result_UpdateShippingOrderDetailInit }),
    [GET_UPDATE_SHIPPING_ORDER_DETAIL_INIT_FAIL]: (error) => ({ error }),
//thay doi trang thai tai xe xe bon
    [GET_UPDATE_SHIPPING_ORDER_TANK_DETAIL_INIT]: (updateOrderStatus) => ({ updateOrderStatus}),
    [GET_UPDATE_SHIPPING_ORDER_TANK_DETAIL_INIT_SUCCESS]: (result_UpdateShippingOrderTankDetailInit) => ({ result_UpdateShippingOrderTankDetailInit }),
    [GET_UPDATE_SHIPPING_ORDER_TANK_DETAIL_INIT_FAIL]: (error) => ({ error }),

    [SET_CREATE_SHIPPING_ORDER_LOCATION]: (shippingOrderDetailID,orderShippingID,lat,long,retimener,createdBy) => ({ shippingOrderDetailID,orderShippingID,lat,long,retimener,createdBy}),
    [SET_CREATE_SHIPPING_ORDER_LOCATION_SUCCESS]: (result_setCreateShippingOrderLocation) => ({ result_setCreateShippingOrderLocation }),
    [SET_CREATE_SHIPPING_ORDER_LOCATION_FAIL]: (error) => ({ error }),
    
    [SET_CREATE_SHIPPING_ORDER_TANK_LOCATION]: (exportOrderDetailID,orderTankID,lat,long,retimener,createdBy) => ({exportOrderDetailID,orderTankID,lat,long,retimener,createdBy}),
    [SET_CREATE_SHIPPING_ORDER_TANK_LOCATION_SUCCESS]: (result_setCreateShippingOrderTankLocation) => ({ result_setCreateShippingOrderTankLocation }),
    [SET_CREATE_SHIPPING_ORDER_TANK_LOCATION_FAIL]: (error) => ({ error }),//tao vi tri tai xe xe bon

    [GET_CREATE_SHIPPING_ORDER_LOCATION]: (orderShippingID) => ({orderShippingID}),
    [GET_CREATE_SHIPPING_ORDER_LOCATION_SUCCESS]: (result_getCreateShippingOrderLocation) => ({ result_getCreateShippingOrderLocation }),
    [GET_CREATE_SHIPPING_ORDER_LOCATION_FAIL]: (error) => ({ error }),

    [GET_LST_CHILDS]: (isChildOf) => ({ isChildOf }),
    [GET_LST_CHILDS_SUCCESS]: (result_getAllChilds) => ({ result_getAllChilds }),
    [GET_LST_CHILDS_FAIL]: (error) => ({ error }),
});

